#!/bin/dash

currDir=$(pwd)

if [ -d ".pushy" ]; then
    echo "pushy-init: error: .pushy already exists"
    exit 1;
else 
    mkdir ".pushy"
    echo "Initialized empty pushy repository in .pushy"
fi
